language: java
jdk:
- oraclejdk8
after_success:
- mvn clean cobertura:cobertura coveralls:report -DrepoToken=$COVERALLS_REPO_TOKEN
- bash <(curl -s https://codecov.io/bash)
before_deploy:
- ./build.sh
deploy:
  provider: releases
  api_key:
    secure: CkPf90QB0OC3PX/Nz2nRyOSWgAAF2jxIlrxeB4VKxWdELYT1xLFmuSaIOMp5CluRRG2VdfNaxFlS/SVlhop0CaUflsiw8gSt7jALcNslhq0ehz+3lTaQvHegPSixkrVUqVQe4Zu7/SsrmUIP/EaJ5EciKxwWY5XbjqRNAGBAEyM=
  file_glob: true
  skip_cleanup: true
  file: 
  - jlifx
  - target/*-jar-with-dependencies.jar
  on:
    tags: true
    all_branches: true
env:
  global:
  - secure: PIbHGVr+Bv0HbK6qOE6C0FrVqcsm/Q6kzFCOa4y9ixT8+2i82DDP4kyyy2ymKevmps+7+SCeJiW8KQkZa7gztSG0h1BoHJo0C6f0xiMYG4kY/7Gq4ZX3mehOVFUymxqhVED/NMK4a7JJxqcSH7JIkBLkuEaueqxc3CmHjI7LCqTr9yMdu/8ulhOeEL/Drg0zsNK9424K6BtxnTh6nNmbNfRnvxCgFc3mLuZ4J6/YN7lBagNiBhpr3XsXdvUC/W89UCcQCIkl/xBKPTxoUGxD6YG+IhapEJrQvqsFkvwFcsUUa9iL7+23QDlK7VGXeKZxwcMYWjRSVai3np94cHZwqivL1okoMFnIjqcAAzX5NOgd0VvM1dUqIwkXQDhp9IPGqDe/H1BiuRb8rmbJyRsxx5YjwksuPugDcG/B24qhyz4NM+gupMx0UE1DXS20xtE1kItEMzCyOJGXDwD9VR13ED0kYkcZoovPFdGFUOpAyAE9UYe1wDpDbmxF8o24tM5ICTcaATpiowWvBmS3i2qsEg8akpxmOqwWK//aOg2aNRiiX5we1H8QK8QNT0MoRf7B9bh59BHL6aOJ/jCeiYXb1jjWGQCGO9Vh3lzJWw2V9f2CvnUaZfeJOCzLgVPqtrI9E1LoPLiVT0Izx9DZ+aINrBxhNfndz5UZ4VQPHF8DDe4=
